host: 0.0.0.0
port: 4000
highlighter: pygments
lsi: false
permalink: /:year/:month/:title.html

url: "http://saladwithsteve.com/"
twitter_username: stevej
github_username: stevej
title: "Steve Jenson's blog"

redcloth:
  hard_breaks: false


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
